# -*- coding: utf-8 -*-
"""Customer Segmentation - Bank Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ozB5fPY_NgSjISrPp8c7bHNgHkjTX3c
"""

# =============================================================
# Customer Segmentation — Bank Churn Dataset
# File: churn_bank_customers.xlsx
# Steps:
#   1. Load & explore data
#   2. Feature engineering & preprocessing
#   3. K-Means clustering (elbow method)
#   4. Segment profiling
#   5. Visualizations
#   6. Retention strategy recommendations
# =============================================================

# pip install pandas scikit-learn matplotlib seaborn openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")

# ── STEP 1: LOAD & EXPLORE ────────────────────────────────────

df = pd.read_excel("churn_bank_customers.xlsx")

print("=" * 55)
print("STEP 1 — Data Overview")
print("=" * 55)
print(f"Shape       : {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Churn rate  : {df['Exited'].mean()*100:.1f}%")
print("\nColumn dtypes:")
print(df.dtypes)
print("\nFirst 3 rows:")
print(df.head(3).to_string())
print("\nDescriptive stats:")
print(df.describe().round(2).to_string())

# Quick churn insight
print("\nChurn by NumOfProducts:")
print((df.groupby("NumOfProducts")["Exited"].mean()*100).round(1).to_string())
print("\nChurn by IsActiveMember:")
print((df.groupby("IsActiveMember")["Exited"].mean()*100).round(1).to_string())


# ── STEP 2: FEATURE ENGINEERING & PREPROCESSING ──────────────

print("\n" + "=" * 55)
print("STEP 2 — Feature Engineering & Preprocessing")
print("=" * 55)

# Encode categoricals
df["Gender_enc"]   = (df["Gender"] == "Male").astype(int)
df["Geo_Germany"]  = (df["Geography"] == "Germany").astype(int)
df["Geo_Spain"]    = (df["Geography"] == "Spain").astype(int)

# Features for clustering (exclude target Exited)
FEATURES = [
    "CreditScore", "Age", "Tenure", "Balance", "NumOfProducts",
    "HasCrCard", "IsActiveMember", "EstimatedSalary",
    "Gender_enc", "Geo_Germany", "Geo_Spain",
]

X = df[FEATURES].copy()

scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(f"Features used : {FEATURES}")
print(f"Scaled matrix : {X_scaled.shape}")


# ── STEP 3: K-MEANS — ELBOW METHOD ───────────────────────────

print("\n" + "=" * 55)
print("STEP 3 — K-Means Clustering (Elbow Method)")
print("=" * 55)

inertias = []
K_RANGE  = range(2, 10)

for k in K_RANGE:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)
    print(f"  k={k}  inertia={km.inertia_:,.0f}")

# Plot elbow
plt.figure(figsize=(7, 4))
plt.plot(list(K_RANGE), inertias, marker="o", color="#3266ad", linewidth=2)
plt.axvline(x=4, color="#E24B4A", linestyle="--", alpha=0.7, label="Chosen k=4")
plt.title("Elbow Method — Optimal k", fontsize=13)
plt.xlabel("Number of clusters (k)")
plt.ylabel("Inertia")
plt.legend()
plt.tight_layout()
plt.savefig("elbow_plot.png", dpi=150)
plt.close()
print("\nElbow plot saved → elbow_plot.png")

# Fit final model
K_FINAL = 4
km_final = KMeans(n_clusters=K_FINAL, random_state=42, n_init=10)
df["Cluster"] = km_final.fit_predict(X_scaled)
print(f"\nFinal model fitted with k={K_FINAL}")
print("Cluster distribution:")
print(df["Cluster"].value_counts().sort_index().to_string())


# ── STEP 4: SEGMENT PROFILING ─────────────────────────────────

print("\n" + "=" * 55)
print("STEP 4 — Segment Profiling")
print("=" * 55)

# ── Business-rule labels (driven by k-means insights) ──
#
#  Dormant     : Balance == 0  (no financial engagement)
#  High-Risk   : Inactive OR 3+ products  (extreme churn drivers)
#  Loyal       : Active + exactly 2 products + CreditScore ≥ 650
#  Moderate    : Everyone else
#
df["Segment"] = "Moderate-Risk"

df.loc[df["Balance"] == 0, "Segment"] = "Dormant"

df.loc[
    (df["Segment"] != "Dormant") &
    ((df["IsActiveMember"] == 0) | (df["NumOfProducts"] >= 3)),
    "Segment",
] = "High-Risk"

df.loc[
    (df["Segment"] == "Moderate-Risk") &
    (df["IsActiveMember"] == 1) &
    (df["NumOfProducts"] == 2) &
    (df["CreditScore"] >= 650),
    "Segment",
] = "Loyal"

# Profile table
PROFILE_COLS = [
    "CreditScore", "Age", "Balance", "NumOfProducts",
    "IsActiveMember", "EstimatedSalary", "Tenure", "Exited",
]
profile = df.groupby("Segment")[PROFILE_COLS].mean().round(2)
profile["Count"]     = df.groupby("Segment").size()
profile["ChurnRate"] = (profile["Exited"] * 100).round(1)

print("\nSegment Profile:")
print(profile[["Count", "ChurnRate", "CreditScore", "Age",
               "Balance", "NumOfProducts", "IsActiveMember", "Tenure"]].to_string())


# ── STEP 5: VISUALIZATIONS ────────────────────────────────────

print("\n" + "=" * 55)
print("STEP 5 — Visualizations")
print("=" * 55)

COLORS = {
    "High-Risk":     "#E24B4A",
    "Dormant":       "#888780",
    "Moderate-Risk": "#378ADD",
    "Loyal":         "#1D9E75",
}
SEGMENT_ORDER = ["Loyal", "Dormant", "Moderate-Risk", "High-Risk"]

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle("Bank Customer Segmentation Dashboard", fontsize=16, fontweight="bold", y=1.01)

# ── 5a: Segment size (donut) ──────────────────────────────────
ax = axes[0, 0]
sizes  = [profile.loc[s, "Count"] for s in SEGMENT_ORDER]
colors = [COLORS[s] for s in SEGMENT_ORDER]
wedges, texts, autotexts = ax.pie(
    sizes, labels=SEGMENT_ORDER, colors=colors,
    autopct="%1.1f%%", startangle=140,
    wedgeprops=dict(width=0.55),
    textprops={"fontsize": 9},
)
for at in autotexts:
    at.set_fontsize(8)
ax.set_title("Segment Distribution", fontweight="bold")

# ── 5b: Churn rate by segment ─────────────────────────────────
ax = axes[0, 1]
churn_vals = [profile.loc[s, "ChurnRate"] for s in SEGMENT_ORDER]
bars = ax.bar(SEGMENT_ORDER, churn_vals,
              color=[COLORS[s] for s in SEGMENT_ORDER],
              edgecolor="white", linewidth=0.8)
ax.set_title("Churn Rate by Segment (%)", fontweight="bold")
ax.set_ylabel("Churn Rate (%)")
ax.set_ylim(0, 45)
for bar, val in zip(bars, churn_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
            f"{val}%", ha="center", va="bottom", fontsize=9, fontweight="bold")
ax.tick_params(axis="x", labelsize=8)

# ── 5c: Active member rate ────────────────────────────────────
ax = axes[0, 2]
active_vals = [profile.loc[s, "IsActiveMember"]*100 for s in SEGMENT_ORDER]
bars = ax.barh(SEGMENT_ORDER, active_vals,
               color=[COLORS[s] for s in SEGMENT_ORDER],
               edgecolor="white")
ax.set_title("Active Member Rate (%)", fontweight="bold")
ax.set_xlabel("% Active")
ax.set_xlim(0, 115)
for bar, val in zip(bars, active_vals):
    ax.text(val + 1, bar.get_y() + bar.get_height()/2,
            f"{val:.1f}%", va="center", fontsize=9)
ax.tick_params(axis="y", labelsize=8)

# ── 5d: Age distribution by segment ──────────────────────────
ax = axes[1, 0]
for seg in SEGMENT_ORDER:
    data = df[df["Segment"] == seg]["Age"]
    ax.hist(data, bins=25, alpha=0.55, label=seg,
            color=COLORS[seg], edgecolor="white", linewidth=0.3)
ax.set_title("Age Distribution by Segment", fontweight="bold")
ax.set_xlabel("Age")
ax.set_ylabel("Count")
ax.legend(fontsize=7)

# ── 5e: Avg balance by segment ────────────────────────────────
ax = axes[1, 1]
bal_vals = [profile.loc[s, "Balance"] for s in SEGMENT_ORDER]
bars = ax.bar(SEGMENT_ORDER, bal_vals,
              color=[COLORS[s] for s in SEGMENT_ORDER],
              edgecolor="white")
ax.set_title("Avg Balance by Segment ($)", fontweight="bold")
ax.set_ylabel("Average Balance ($)")
for bar, val in zip(bars, bal_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 500,
            f"${val:,.0f}", ha="center", va="bottom", fontsize=7.5)
ax.tick_params(axis="x", labelsize=8)

# ── 5f: PCA scatter (2D cluster view) ────────────────────────
ax = axes[1, 2]
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)
df["PCA1"] = X_pca[:, 0]
df["PCA2"] = X_pca[:, 1]

sample = df.sample(1000, random_state=42)
for seg in SEGMENT_ORDER:
    sub = sample[sample["Segment"] == seg]
    ax.scatter(sub["PCA1"], sub["PCA2"],
               c=COLORS[seg], label=seg,
               alpha=0.45, s=12, edgecolors="none")
ax.set_title(
    f"PCA Cluster View\n(explains {sum(pca.explained_variance_ratio_)*100:.1f}% variance)",
    fontweight="bold"
)
ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.legend(fontsize=7, markerscale=2)

plt.tight_layout()
plt.savefig("segmentation_dashboard.png", dpi=150, bbox_inches="tight")
plt.close()
print("Dashboard saved → segmentation_dashboard.png")


# ── STEP 6: RETENTION STRATEGY RECOMMENDATIONS ───────────────

print("\n" + "=" * 55)
print("STEP 6 — Retention Strategy Recommendations")
print("=" * 55)

strategies = {
    "High-Risk": {
        "count":   int(profile.loc["High-Risk", "Count"]),
        "churn":   profile.loc["High-Risk", "ChurnRate"],
        "profile": "Inactive members (IsActiveMember=0) OR customers with 3+ products. "
                   "Avg balance ~$120K. Churn rate 33.3% — highest of all segments.",
        "actions": [
            "Immediate outreach: personal banker call within 48h for inactive accounts",
            "Re-engagement offer: fee waiver or bonus interest rate for 3 months",
            "Product review: simplify portfolios — reduce 3-4 product holders to 2 optimal ones",
            "Loyalty incentives: cashback or points programme to rebuild engagement",
            "Predictive alert: flag when IsActiveMember flips to 0 and trigger workflow",
        ],
    },
    "Dormant": {
        "count":   int(profile.loc["Dormant", "Count"]),
        "churn":   profile.loc["Dormant", "ChurnRate"],
        "profile": "Zero-balance customers. Avg salary ~$99K — they have money, just not with us. "
                   "Churn rate 13.8% but high silent attrition risk.",
        "actions": [
            "Deposit incentive: promotional interest rate (e.g. 5% for 6 months) to fund accounts",
            "Salary crediting campaign: payroll deposit bonus to create recurring engagement",
            "Mobile app push: personalised nudges showing savings goals and milestones",
            "Cross-sell: entry-level investment product aligned to their salary bracket",
            "Win-back: email series — 'Your account is ready when you are'",
        ],
    },
    "Moderate-Risk": {
        "count":   int(profile.loc["Moderate-Risk", "Count"]),
        "churn":   profile.loc["Moderate-Risk", "ChurnRate"],
        "profile": "Engaged customers with 1 product but not yet maximising relationship. "
                   "Avg balance ~$119K. Churn 16.1% — preventable with the right nudge.",
        "actions": [
            "Product upsell: introduce credit card or savings account to deepen relationship",
            "Financial health check: free annual review to build trust and stickiness",
            "Milestone rewards: tenure-based perks at 3, 5, 10-year marks",
            "Digital engagement: enrol in mobile banking features (budgeting, analytics)",
            "Referral programme: reward existing customers for bringing new accounts",
        ],
    },
    "Loyal": {
        "count":   int(profile.loc["Loyal", "Count"]),
        "churn":   profile.loc["Loyal", "ChurnRate"],
        "profile": "Active members with 2 products and credit score ≥ 650. "
                   "Churn only 9.3%. Premium customers — protect and expand.",
        "actions": [
            "VIP programme: dedicated relationship manager and priority service",
            "Exclusive rates: preferential mortgage/loan rates for long-term retention",
            "Advocacy: referral bonuses — they are the best brand ambassadors",
            "Premium upgrade: offer premium/black card tier with added benefits",
            "Early access: beta features, new products, exclusive events",
        ],
    },
}

for seg, info in strategies.items():
    print(f"\n{'─'*55}")
    print(f"  {seg.upper()}  |  n={info['count']:,}  |  Churn={info['churn']}%")
    print(f"{'─'*55}")
    print(f"  Profile: {info['profile']}")
    print(f"\n  Recommended Actions:")
    for i, action in enumerate(info["actions"], 1):
        print(f"    {i}. {action}")

# ── Export labelled dataset ───────────────────────────────────
out_cols = [
    "CustomerId", "Surname", "Geography", "Gender",
    "CreditScore", "Age", "Tenure", "Balance",
    "NumOfProducts", "HasCrCard", "IsActiveMember",
    "EstimatedSalary", "Exited", "Cluster", "Segment",
]
df[out_cols].to_excel("customers_segmented.xlsx", index=False)
print(f"\n{'='*55}")
print("Labelled dataset saved → customers_segmented.xlsx")
print(f"{'='*55}")
print("\nDone. Output files:")
print("  • elbow_plot.png")
print("  • segmentation_dashboard.png")
print("  • customers_segmented.xlsx")