# -*- coding: utf-8 -*-
"""Exploratory Data Analysis - Chrun Bank Customers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pW39uODgMSc2CXbbJmQ7ojlvjzs9vHe0
"""

#STEP 1 - DATA OVERVIEW
import pandas as pd

def generate_data_overview(file_path):
    """
    Loads an Excel file and prints its shape, column data types,
    null counts, null percentages, and complete summary statistics.
    """
    # Load the Excel file dynamically using the file_path variable
    try:
        df = pd.read_excel(file_path)
    except Exception as e:
        print(f"Error loading file: {e}")
        return None

    print("=" * 70)
    print(f"📊 DATA OVERVIEW FOR: {file_path}")
    print("=" * 70)

    # 1. Shape of the Dataset
    print(f"\n[1] DATASET SHAPE")
    print(f"• Total Rows (Observations): {df.shape[0]}")
    print(f"• Total Columns (Features): {df.shape[1]}")
    print("-" * 70)

    # 2. Column-level Metadata (Data Types & Missing Values)
    print(f"\n[2] COLUMN METADATA (DTYPES & NULLS)")
    metadata_df = pd.DataFrame({
        'Data Type': df.dtypes,
        'Null Count': df.isnull().sum(),
        'Null Percentage (%)': (df.isnull().sum() / len(df) * 100).round(2)
    })
    print(metadata_df)
    print("-" * 70)

    # 3. Complete Summary Statistics
    print(f"\n[3] SUMMARY STATISTICS (ALL COLUMNS)")
    summary_stats = df.describe(include='all')
    print(summary_stats)
    print("=" * 70)

    return df

# --- How to run it ---
# You pass the actual string name of your file right here!
df = generate_data_overview('churn_bank_customers.xlsx')

#STEP 2 - TARGET VARIABLE
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'df' is the DataFrame returned from your previous step
# df = generate_data_overview('churn_bank_customers.xlsx')

def check_target_imbalance(df, target_col='Exited'):
    """
    Plots the distribution of the target variable and prints class percentages
    to quickly check for class imbalance.
    """
    # 1. Calculate absolute counts and relative percentages
    counts = df[target_col].value_counts()
    percentages = df[target_col].value_counts(normalize=True) * 100

    print("=" * 50)
    print(f"📊 CLASS DISTRIBUTION FOR '{target_col}'")
    print("=" * 50)
    for idx in counts.index:
        print(f"Class {idx}: {counts[idx]} rows ({percentages[idx]:.2f}%)")
    print("=" * 50)

    # 2. Generate the Seaborn Countplot
    plt.figure(figsize=(6, 6))

    # Create the countplot
    ax = sns.countplot(x=target_col, data=df, palette='Set2')

    # Add percentage labels on top of the bars for quick scanning
    total = len(df)
    for p in ax.patches:
        percentage = f'{100 * p.get_height() / total:.1f}%'
        x_coord = p.get_x() + p.get_width() / 2 - 0.1
        y_coord = p.get_height() + (total * 0.01) # dynamic padding above bar
        ax.annotate(percentage, (x_coord, y_coord), fontsize=10, weight='bold')

    plt.title(f'Distribution of Target Variable ({target_col})', fontsize=12, pad=15)
    plt.xlabel('Customer Status (0 = Retained, 1 = Exited)', fontsize=10)
    plt.ylabel('Count', fontsize=10)
    plt.tight_layout()

    # Display the plot
    plt.show()

# Run the function
check_target_imbalance(df, target_col='Exited')

#STEP 3 - UNIVARIATE ANALYSIS
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================================
# 1. DEFINE THE UNIVARIATE ANALYSIS FUNCTIONS
# =====================================================================

def plot_numeric_distributions(df, numeric_cols):
    """
    Generates a grid of histograms with Kernel Density Estimate (KDE) lines
    for numeric features to understand their shapes and spreads.
    """
    print("=" * 70)
    print("📈 GENERATING HISTOGRAMS FOR NUMERIC FEATURES")
    print("=" * 70)

    # Calculate optimal grid layout rows based on number of columns
    num_plots = len(numeric_cols)
    rows = (num_plots + 1) // 2  # Arrange in 2 columns

    fig, axes = plt.subplots(rows, 2, figsize=(14, rows * 4))
    axes = axes.flatten()  # Flatten the 2D grid matrix into a 1D array for easy looping

    for i, col in enumerate(numeric_cols):
        if col in df.columns:
            # kde=True adds a smooth probability density curve over the histogram bars
            sns.histplot(data=df, x=col, kde=True, ax=axes[i], color='skyblue', bins=30)
            axes[i].set_title(f'Distribution of {col}', fontsize=12, pad=10)
            axes[i].set_xlabel('')
            axes[i].set_ylabel('Count')
        else:
            axes[i].set_visible(False) # Hide extra empty subplots if columns don't match

    # Hide any unused subplots at the end of the grid
    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)

    plt.suptitle('Univariate Analysis: Numeric Distributions', fontsize=16, weight='bold', y=1.02)
    plt.tight_layout()
    plt.show()


def plot_categorical_distributions(df, categorical_cols):
    """
    Generates a grid of bar charts for categorical features to evaluate
    frequency counts and look for class imbalances.
    """
    print("\n" + "=" * 70)
    print("📊 GENERATING BAR CHARTS FOR CATEGORICAL FEATURES")
    print("=" * 70)

    num_plots = len(categorical_cols)
    rows = (num_plots + 1) // 2

    fig, axes = plt.subplots(rows, 2, figsize=(14, rows * 4))
    axes = axes.flatten()

    for i, col in enumerate(categorical_cols):
        if col in df.columns:
            # Generate value counts for text output reference
            print(f"\nValue Counts for {col}:")
            print(df[col].value_counts())

            # Create countplot (bar chart)
            sns.countplot(data=df, x=col, ax=axes[i], palette='Set2', order=df[col].value_counts().index)
            axes[i].set_title(f'Count of {col}', fontsize=12, pad=10)
            axes[i].set_xlabel('')
            axes[i].set_ylabel('Count')

            # Rotate labels if categories are long string names
            if df[col].nunique() > 3:
                axes[i].set_xticklabels(axes[i].get_xticklabels(), rotation=30, ha='right')
        else:
            axes[i].set_visible(False)

    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)

    plt.suptitle('Univariate Analysis: Categorical Value Counts', fontsize=16, weight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

# =====================================================================
# 2. LOAD DATA AND EXECUTE THE CALLS
# =====================================================================

# Step A: Load your dataset
df = pd.read_excel('churn_bank_customers.xlsx')

# Step B: Define columns to test (spelled exactly as they appear in the file)
numeric_features = ['Age', 'Balance', 'CreditScore', 'EstimatedSalary', 'Tenure']
categorical_features = ['Geography', 'Gender', 'NumOfProducts', 'HasCrCard', 'IsActiveMember']

# Step C: Call functions to output graphs immediately
plot_numeric_distributions(df, numeric_features)
plot_categorical_distributions(df, categorical_features)

#STEP 4 - Bivariate Analysis (vs. Churn)
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# 1. DEFINE THE ANALYSIS FUNCTIONS
# ==========================================

def analyze_categorical_churn(df, cat_column, target_col='Exited'):
    print("\n" + "=" * 60)
    print(f"📊 CHURN RATE BY {cat_column.upper()}")
    print("=" * 60)

    churn_rates = df.groupby(cat_column)[target_col].agg(['count', 'mean']).rename(
        columns={'mean': 'Churn Rate', 'count': 'Total Customers'}
    )
    churn_rates['Churn Rate (%)'] = (churn_rates['Churn Rate'] * 100).round(2)
    print(churn_rates)

    plt.figure(figsize=(6, 4))
    ax = sns.barplot(x=cat_column, y=target_col, data=df, palette='Blues_d', errorbar=None)

    # Add labels to bars
    for p in ax.patches:
        ax.annotate(f'{p.get_height()*100:.1f}%',
                    (p.get_x() + p.get_width() / 2., p.get_height() + 0.01),
                    ha='center', va='center', weight='bold', fontsize=10)

    plt.title(f'Churn Rate by {cat_column}')
    plt.tight_layout()
    plt.show()


def analyze_numeric_churn(df, num_column, target_col='Exited'):
    print("\n" + "=" * 60)
    print(f"📈 NUMERIC DISTRIBUTION: {num_column.upper()} by CHURN STATUS")
    print("=" * 60)

    summary = df.groupby(target_col)[num_column].describe().round(2)
    print(summary)

    plt.figure(figsize=(6, 4))
    sns.boxplot(x=target_col, y=num_column, data=df, palette='Set2')
    plt.title(f'Distribution of {num_column} by Churn Status')
    plt.xticks([0, 1], ['Retained (0)', 'Exited (1)'])
    plt.tight_layout()
    plt.show()

# ==========================================
# 2. RUN THE CODE (The "Function Calls")
# ==========================================

# Step A: Load your actual dataset
# (Make sure this file is in the same folder where you are running your Python script!)
df = pd.read_excel('churn_bank_customers.xlsx')

# Step B: Call the functions with the columns you want to inspect
# Analyzing a categorical column:
analyze_categorical_churn(df, cat_column='Geography')

# Analyzing a numerical column:
analyze_numeric_churn(df, num_column='Age')

#Step 5 — Correlation Analysis

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'df' is your loaded DataFrame containing 'churn_bank_customers.xlsx'
# df = pd.read_excel('churn_bank_customers.xlsx')

def plot_correlation_heatmap(df):
    """
    Isolates numeric columns, calculates Pearson correlation,
    and plots a clean Seaborn heatmap.
    """
    print("=" * 60)
    print("🔮 CALCULATING CORRELATION MATRIX")
    print("=" * 60)

    # 1. Filter out categorical columns (Heatmaps require numbers)
    numeric_df = df.select_dtypes(include=['int64', 'float64'])

    # 2. Compute the Pearson correlation matrix
    corr_matrix = numeric_df.corr()

    # Display raw numbers in console for precise reading
    print(corr_matrix.round(2))
    print("-" * 60)

    # 3. Setup the Matplotlib figure
    plt.figure(figsize=(10, 8))

    # 4. Generate Heatmap
    # 'annot=True' displays the values inside the squares
    # 'cmap' sets a diverging color scale (coolwarm perfectly highlights -1 vs +1)
    # 'fmt=".2f"' forces 2 decimal places
    # 'vmin' and 'vmax' anchor the colorbar limits firmly between -1 and 1
    sns.heatmap(
        corr_matrix,
        annot=True,
        cmap='coolwarm',
        fmt=".2f",
        linewidths=0.5,
        vmin=-1,
        vmax=1,
        square=True
    )

    plt.title('Correlation Matrix of Numeric Features', fontsize=14, pad=20)
    plt.xticks(rotation=45, ha='right') # Tilt X-axis labels to prevent overlapping
    plt.yticks(rotation=0)
    plt.tight_layout()

    # 5. Display the plot
    plt.show()

# Run the function
plot_correlation_heatmap(df)

#Step 6 — Key Segment Deep-Dives

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================================
# 1. DEFINE THE SEGMENT DEEP-DIVE FUNCTIONS
# =====================================================================

def segment_crosstab_dive(df):
    print("=" * 70)
    print("📋 CHURN RATES BY GEOGRAPHY AND GENDER")
    print("=" * 70)

    # Generates a matrix table of intersecting churn averages
    segmented_rates = pd.crosstab(
        index=df['Geography'],
        columns=df['Gender'],
        values=df['Exited'],
        aggfunc='mean'
    ) * 100  # Convert decimals to clean percentages

    print(segmented_rates.round(2).astype(str) + '%')
    print("=" * 70)


def plot_multi_variable_segments(df):
    print("\n🎨 GENERATING MULTI-VARIABLE FACET PLOT...")

    # This automatically instantiates a FacetGrid layout behind the scenes
    g = sns.catplot(
        data=df,
        x="Gender",
        y="Exited",
        hue="IsActiveMember",
        col="Geography",
        kind="bar",
        palette="muted",
        errorbar=None,
        height=4,
        aspect=0.8
    )

    # Formatting layout settings across all generated subplots
    g.set_ylabels("Churn Rate (Decimal %)")
    g.set_titles("{col_name} Market")

    plt.subplots_adjust(top=0.8)
    g.fig.suptitle('Segment Deep-Dive: Churn Rate by Gender, Activity, and Geography', fontsize=12, weight='bold')

    # This forces the windows to display the visual plots
    plt.show()

# =====================================================================
# 2. LOAD DATA AND EXECUTE (The "Calls")
# =====================================================================

# Step A: Load your dataset
df = pd.read_excel('churn_bank_customers.xlsx')

# Step B: Call the functions to execute the operations
segment_crosstab_dive(df)
plot_multi_variable_segments(df)

"""📋 Summary of Findings — Bank Customer Churn EDA

Step 1 — Data Overview

Dataset has 10,000 rows and 14 columns
Zero missing values across all columns — no cleaning needed
Mix of numeric (Age, Balance, CreditScore, Salary, Tenure) and categorical (Geography, Gender, NumOfProducts, HasCrCard, IsActiveMember) features


Step 2 — Target Variable

79.6% retained vs 20.4% churned — the dataset is imbalanced
This matters if you move to ML next — you'll need to handle this imbalance (e.g. SMOTE or class weights)


Step 3 — Univariate Analysis

Age ranges from 18–92, average 38.9 — mostly working-age adults
Balance has a wide spread (0 to 250K) — many customers have €0 balance (bottom 25% = 0)
France dominates the dataset (5,014 customers) vs Germany (2,509) and Spain (2,477)
Males slightly outnumber females (5,457 vs 4,543)
Most customers hold 1 or 2 products — very few have 3 or 4


Step 4 — Bivariate Analysis (the most insights)
FeatureKey FindingGeographyGermany churns at 32.4% — double France (16.2%) and Spain (16.7%)GenderFemales churn at 25.1% vs males at 16.5%NumOfProducts2 products = lowest churn (7.6%) — 3 or 4 products = extremely high (83–100%)IsActiveMemberInactive = 26.9% churn vs active = 14.3%HasCrCardNearly identical churn (20.8% vs 20.2%) — not a useful predictorAgeChurned customers average 44.8 years vs 37.4 for retained — older customers leave moreBalanceChurned customers hold higher balances (€91K vs €73K) — high-value customers are leavingCreditScore, Salary, TenureAlmost no difference between churned and retained — not useful predictors

Step 5 — Correlation Analysis

Age has the strongest positive correlation with churn (r = 0.29)
IsActiveMember has the strongest negative correlation (r = -0.16) — activity protects against churn
Balance has a weak positive correlation (r = 0.12)
CreditScore, Tenure, Salary, HasCrCard all near r ≈ 0 — essentially no linear relationship with churn


Step 6 — Segment Deep-Dives

German females are the highest risk group at 37.6% churn
German inactive females are the most extreme: 44.6% churn rate
Across all geographies, inactive members consistently churn more — being active roughly halves churn risk
Spain and France behave similarly; Germany is a clear outlier in every segment


💡 Bottom Line — Top 5 Factors to Act On

NumOfProducts 3–4 → investigate over-selling or poor product fit
Germany → country-specific issue needs dedicated investigation
Age 40+ → build a targeted retention program for older customers
Inactive members → re-engagement campaigns before they churn
Female customers → higher churn across all geographies, especially Germany


"""