# -*- coding: utf-8 -*-
"""Visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I958rgh7_CcGphCZ5-EhVKVnUMHXZp2l
"""

"""
Module 4 — Churn Visualization Dashboard
=========================================
Charts:
  1. Churn Rate by Geography        (bar + pie)
  2. Churn Rate by Age Group        (histogram overlay + line)
  3. Churn Rate by Number of Products (grouped bar)
  4. Bonus: Churn by Gender × Geography (heatmap)

Requirements:
  pip install pandas matplotlib seaborn plotly openpyxl
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ── 0. Load data ──────────────────────────────────────────────────────────────
FILE = "churn_bank_customers.xlsx"          # ← change path if needed
df = pd.read_excel(FILE)

# Friendly label
df["Churn"] = df["Exited"].map({1: "Churned", 0: "Retained"})

# Age groups
bins   = [18, 30, 40, 50, 60, 100]
labels = ["18-30", "31-40", "41-50", "51-60", "60+"]
df["AgeGroup"] = pd.cut(df["Age"], bins=bins, labels=labels, right=True)


# ══════════════════════════════════════════════════════════════════════════════
# SECTION A — Static dashboard (Matplotlib + Seaborn)
# ══════════════════════════════════════════════════════════════════════════════

PALETTE   = {"Churned": "#E74C3C", "Retained": "#2ECC71"}
BG        = "#F8F9FA"
ACCENT    = "#2C3E50"

fig = plt.figure(figsize=(18, 14), facecolor=BG)
fig.suptitle("Bank Customer Churn Dashboard", fontsize=22,
             fontweight="bold", color=ACCENT, y=0.98)
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

# ── A1. Churn Rate by Geography (bar) ─────────────────────────────────────────
ax1 = fig.add_subplot(gs[0, 0])
geo = (df.groupby(["Geography", "Churn"])
         .size()
         .reset_index(name="Count"))
geo_pct = geo.copy()
totals  = geo.groupby("Geography")["Count"].transform("sum")
geo_pct["Pct"] = geo["Count"] / totals * 100

churned_geo = geo_pct[geo_pct["Churn"] == "Churned"]
bars = ax1.bar(churned_geo["Geography"], churned_geo["Pct"],
               color=["#E74C3C", "#E67E22", "#C0392B"], edgecolor="white",
               linewidth=1.5, zorder=3)
ax1.set_facecolor(BG)
ax1.yaxis.grid(True, linestyle="--", alpha=0.5, zorder=0)
ax1.set_xlabel("Geography", fontweight="bold")
ax1.set_ylabel("Churn Rate (%)", fontweight="bold")
ax1.set_title("Churn Rate by Geography", fontsize=13, fontweight="bold",
              color=ACCENT)
for bar, val in zip(bars, churned_geo["Pct"]):
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
             f"{val:.1f}%", ha="center", va="bottom", fontweight="bold",
             fontsize=11)
ax1.set_ylim(0, churned_geo["Pct"].max() * 1.25)
sns.despine(ax=ax1, left=True)

# ── A2. Geography Pie ──────────────────────────────────────────────────────────
ax2 = fig.add_subplot(gs[0, 1])
geo_counts = df[df["Exited"] == 1]["Geography"].value_counts()
explode = [0.05] * len(geo_counts)
wedges, texts, autotexts = ax2.pie(
    geo_counts, labels=geo_counts.index, autopct="%1.1f%%",
    colors=["#E74C3C", "#E67E22", "#C0392B"], explode=explode,
    startangle=140, pctdistance=0.8,
    wedgeprops={"edgecolor": "white", "linewidth": 2})
for at in autotexts:
    at.set_fontsize(11); at.set_fontweight("bold"); at.set_color("white")
ax2.set_title("Churned Customers\nby Geography", fontsize=13,
              fontweight="bold", color=ACCENT)

# ── A3. Churn Rate by Age Group (line + bar) ──────────────────────────────────
ax3 = fig.add_subplot(gs[0, 2])
age_stats = (df.groupby("AgeGroup", observed=True)["Exited"]
               .agg(Total="count", Churned="sum")
               .reset_index())
age_stats["ChurnRate"] = age_stats["Churned"] / age_stats["Total"] * 100

color_bars = [plt.cm.RdYlGn_r(v / 100) for v in age_stats["ChurnRate"]]
ax3.bar(age_stats["AgeGroup"].astype(str), age_stats["ChurnRate"],
        color=color_bars, edgecolor="white", linewidth=1.5, zorder=3)
ax3b = ax3.twinx()
ax3b.plot(age_stats["AgeGroup"].astype(str), age_stats["Total"],
          color=ACCENT, marker="o", linewidth=2, label="Total customers")
ax3b.set_ylabel("Total Customers", color=ACCENT, fontweight="bold")
ax3b.tick_params(axis="y", labelcolor=ACCENT)
ax3.set_facecolor(BG)
ax3.yaxis.grid(True, linestyle="--", alpha=0.5, zorder=0)
ax3.set_xlabel("Age Group", fontweight="bold")
ax3.set_ylabel("Churn Rate (%)", fontweight="bold", color="#E74C3C")
ax3.tick_params(axis="y", labelcolor="#E74C3C")
ax3.set_title("Churn Rate by Age Group", fontsize=13, fontweight="bold",
              color=ACCENT)
sns.despine(ax=ax3, right=False)

# ── A4. Churn by Number of Products (grouped bar) ─────────────────────────────
ax4 = fig.add_subplot(gs[1, 0:2])
prod = (df.groupby(["NumOfProducts", "Churn"])
          .size()
          .reset_index(name="Count"))
prod_piv = prod.pivot(index="NumOfProducts", columns="Churn",
                      values="Count").fillna(0)
x      = range(len(prod_piv))
width  = 0.35
rects1 = ax4.bar([i - width/2 for i in x], prod_piv.get("Retained", 0),
                 width, label="Retained", color="#2ECC71",
                 edgecolor="white", linewidth=1.5, zorder=3)
rects2 = ax4.bar([i + width/2 for i in x], prod_piv.get("Churned", 0),
                 width, label="Churned", color="#E74C3C",
                 edgecolor="white", linewidth=1.5, zorder=3)
ax4.set_xticks(list(x))
ax4.set_xticklabels([f"{p} Product{'s' if p > 1 else ''}"
                     for p in prod_piv.index])
ax4.set_facecolor(BG)
ax4.yaxis.grid(True, linestyle="--", alpha=0.5, zorder=0)
ax4.set_xlabel("Number of Products", fontweight="bold")
ax4.set_ylabel("Customer Count", fontweight="bold")
ax4.set_title("Churned vs Retained by Number of Products",
              fontsize=13, fontweight="bold", color=ACCENT)
ax4.legend(fontsize=11)

# churn rate labels above churned bars
for rect, prod_idx in zip(rects2, prod_piv.index):
    total = prod_piv.loc[prod_idx, "Retained"] + prod_piv.loc[prod_idx, "Churned"]
    rate  = prod_piv.loc[prod_idx, "Churned"] / total * 100
    ax4.text(rect.get_x() + rect.get_width() / 2,
             rect.get_height() + 20, f"{rate:.0f}%",
             ha="center", fontsize=10, color="#E74C3C", fontweight="bold")
sns.despine(ax=ax4, left=True)

# ── A5. Heatmap: Gender × Geography churn rate ────────────────────────────────
ax5 = fig.add_subplot(gs[1, 2])
heat = (df.groupby(["Gender", "Geography"])["Exited"]
          .mean()
          .mul(100)
          .unstack())
sns.heatmap(heat, ax=ax5, annot=True, fmt=".1f", cmap="RdYlGn_r",
            linewidths=0.5, linecolor="white",
            annot_kws={"size": 12, "weight": "bold"},
            cbar_kws={"label": "Churn Rate (%)"})
ax5.set_title("Churn Rate %\nGender × Geography",
              fontsize=13, fontweight="bold", color=ACCENT)
ax5.set_xlabel("Geography", fontweight="bold")
ax5.set_ylabel("Gender", fontweight="bold")

plt.savefig("churn_dashboard_static.png", dpi=150, bbox_inches="tight",
            facecolor=BG)
plt.show()
print("✅ Saved: churn_dashboard_static.png")


# ══════════════════════════════════════════════════════════════════════════════
# SECTION B — Interactive dashboard (Plotly)
# ══════════════════════════════════════════════════════════════════════════════

fig_px = make_subplots(
    rows=2, cols=2,
    subplot_titles=[
        "Churn Rate by Geography",
        "Churn Rate by Age Group",
        "Churned vs Retained by # Products",
        "Churn Rate — Gender × Geography",
    ],
    specs=[
        [{"type": "bar"}, {"type": "bar"}],
        [{"type": "bar"}, {"type": "heatmap"}],
    ],
    vertical_spacing=0.18,
    horizontal_spacing=0.12,
)

# B1. Geography bar
fig_px.add_trace(
    go.Bar(
        x=churned_geo["Geography"],
        y=churned_geo["Pct"].round(1),
        marker_color=["#E74C3C", "#E67E22", "#C0392B"],
        text=churned_geo["Pct"].round(1).astype(str) + "%",
        textposition="outside",
        name="Churn Rate",
        showlegend=False,
    ),
    row=1, col=1,
)

# B2. Age Group bar
fig_px.add_trace(
    go.Bar(
        x=age_stats["AgeGroup"].astype(str),
        y=age_stats["ChurnRate"].round(1),
        marker_color=age_stats["ChurnRate"],
        marker_colorscale="RdYlGn_r",
        text=age_stats["ChurnRate"].round(1).astype(str) + "%",
        textposition="outside",
        name="Churn Rate",
        showlegend=False,
    ),
    row=1, col=2,
)

# B3. Products grouped bar
for status, color in [("Retained", "#2ECC71"), ("Churned", "#E74C3C")]:
    if status in prod_piv.columns:
        fig_px.add_trace(
            go.Bar(
                x=[f"{p} Prod." for p in prod_piv.index],
                y=prod_piv[status].values,
                name=status,
                marker_color=color,
                legendgroup=status,
                showlegend=True,
            ),
            row=2, col=1,
        )

# B4. Heatmap gender × geo
fig_px.add_trace(
    go.Heatmap(
        z=heat.values,
        x=heat.columns.tolist(),
        y=heat.index.tolist(),
        colorscale="RdYlGn_r",
        text=[[f"{v:.1f}%" for v in row] for row in heat.values],
        texttemplate="%{text}",
        showscale=True,
        name="Churn %",
        showlegend=False,
    ),
    row=2, col=2,
)

fig_px.update_layout(
    title_text="🏦 Bank Customer Churn — Interactive Dashboard",
    title_font_size=20,
    height=750,
    paper_bgcolor="#F8F9FA",
    plot_bgcolor="#F8F9FA",
    barmode="group",
    legend=dict(orientation="h", yanchor="bottom", y=1.02,
                xanchor="right", x=1),
    font=dict(family="Arial", size=12),
)
fig_px.update_yaxes(title_text="Churn Rate (%)", row=1, col=1)
fig_px.update_yaxes(title_text="Churn Rate (%)", row=1, col=2)
fig_px.update_yaxes(title_text="Customers",      row=2, col=1)

fig_px.write_html("churn_dashboard_interactive.html")
fig_px.show()
print("✅ Saved: churn_dashboard_interactive.html")